package bean;
// Generated 16/09/2023 15:43:39 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GhsProdutos generated by hbm2java
 */
@Entity
@Table(name="ghs_produtos"
    ,catalog="db_gabrielh"
)
public class GhsProdutos  implements java.io.Serializable {


     private int idghsProdutos;
     private String ghsNome;
     private String ghsDescricao;
     private Double ghsPreco;
     private int ghsQuantidade;
     private float ghsValorUnitario;
     private Set ghsVendasProdutoses = new HashSet(0);

    public GhsProdutos() {
    }

	
    public GhsProdutos(int idghsProdutos, String ghsNome, String ghsDescricao, Double ghsPreco, int ghsQuantidade, float ghsValorUnitario) {
        this.idghsProdutos = idghsProdutos;
        this.ghsNome = ghsNome;
        this.ghsDescricao = ghsDescricao;
        this.ghsPreco = ghsPreco;
        this.ghsQuantidade = ghsQuantidade;
        this.ghsValorUnitario = ghsValorUnitario;
    }
    public GhsProdutos(int idghsProdutos, String ghsNome, String ghsDescricao, Double ghsPreco, int ghsQuantidade, float ghsValorUnitario, Set ghsVendasProdutoses) {
       this.idghsProdutos = idghsProdutos;
       this.ghsNome = ghsNome;
       this.ghsDescricao = ghsDescricao;
       this.ghsPreco = ghsPreco;
       this.ghsQuantidade = ghsQuantidade;
       this.ghsValorUnitario = ghsValorUnitario;
       this.ghsVendasProdutoses = ghsVendasProdutoses;
    }
   
     @Id 

    
    @Column(name="idghs_produtos", unique=true, nullable=false)
    public int getIdghsProdutos() {
        return this.idghsProdutos;
    }
    
    public void setIdghsProdutos(int idghsProdutos) {
        this.idghsProdutos = idghsProdutos;
    }

    
    @Column(name="ghs_nome", nullable=false, length=50)
    public String getGhsNome() {
        return this.ghsNome;
    }
    
    public void setGhsNome(String ghsNome) {
        this.ghsNome = ghsNome;
    }

    
    @Column(name="ghs_descricao", nullable=false, length=150)
    public String getGhsDescricao() {
        return this.ghsDescricao;
    }
    
    public void setGhsDescricao(String ghsDescricao) {
        this.ghsDescricao = ghsDescricao;
    }

    
    @Column(name="ghs_preco", nullable=false, precision=7)
    public Double getGhsPreco() {
        return this.ghsPreco;
    }
    
    public void setGhsPreco(Double ghsPreco) {
        this.ghsPreco = ghsPreco;
    }

    
    @Column(name="ghs_quantidade", nullable=false)
    public int getGhsQuantidade() {
        return this.ghsQuantidade;
    }
    
    public void setGhsQuantidade(int ghsQuantidade) {
        this.ghsQuantidade = ghsQuantidade;
    }

    
    @Column(name="ghs_valorUnitario", nullable=false, precision=12, scale=0)
    public float getGhsValorUnitario() {
        return this.ghsValorUnitario;
    }
    
    public void setGhsValorUnitario(float ghsValorUnitario) {
        this.ghsValorUnitario = ghsValorUnitario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ghsProdutos")
    public Set getGhsVendasProdutoses() {
        return this.ghsVendasProdutoses;
    }
    
    public void setGhsVendasProdutoses(Set ghsVendasProdutoses) {
        this.ghsVendasProdutoses = ghsVendasProdutoses;
    }




}


