package bean;
// Generated 23/10/2023 15:42:33 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GhsUsuarios generated by hbm2java
 */
@Entity
@Table(name="ghs_usuarios"
    ,catalog="db_gabrielh"
    //db_gabriel_corrales
)
public class GhsUsuarios  implements java.io.Serializable {


     private int idgbsUsuarios;
     private String gbsNome;
     private String gbsApelido;
     private String gbsCpf;
     private Date gbsDataNascimento;
     private String gbsSenha;
     private int gbsNivel;
     private String gbsAtivo;

    public GhsUsuarios() {
    }

    public GhsUsuarios(int idgbsUsuarios, String gbsNome, String gbsApelido, String gbsCpf, Date gbsDataNascimento, String gbsSenha, int gbsNivel, String gbsAtivo) {
       this.idgbsUsuarios = idgbsUsuarios;
       this.gbsNome = gbsNome;
       this.gbsApelido = gbsApelido;
       this.gbsCpf = gbsCpf;
       this.gbsDataNascimento = gbsDataNascimento;
       this.gbsSenha = gbsSenha;
       this.gbsNivel = gbsNivel;
       this.gbsAtivo = gbsAtivo;
    }
   
     @Id 

    
    @Column(name="idgbs_usuarios", unique=true, nullable=false)
    public int getIdgbsUsuarios() {
        return this.idgbsUsuarios;
    }
    
    public void setIdgbsUsuarios(int idgbsUsuarios) {
        this.idgbsUsuarios = idgbsUsuarios;
    }

    
    @Column(name="gbs_nome", nullable=false, length=100)
    public String getGbsNome() {
        return this.gbsNome;
    }
    
    public void setGbsNome(String gbsNome) {
        this.gbsNome = gbsNome;
    }

    
    @Column(name="gbs_apelido", nullable=false, length=50)
    public String getGbsApelido() {
        return this.gbsApelido;
    }
    
    public void setGbsApelido(String gbsApelido) {
        this.gbsApelido = gbsApelido;
    }

    
    @Column(name="gbs_cpf", nullable=false, length=14)
    public String getGbsCpf() {
        return this.gbsCpf;
    }
    
    public void setGbsCpf(String gbsCpf) {
        this.gbsCpf = gbsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gbs_dataNascimento", nullable=false, length=10)
    public Date getGbsDataNascimento() {
        return this.gbsDataNascimento;
    }
    
    public void setGbsDataNascimento(Date gbsDataNascimento) {
        this.gbsDataNascimento = gbsDataNascimento;
    }

    
    @Column(name="gbs_senha", nullable=false, length=20)
    public String getGbsSenha() {
        return this.gbsSenha;
    }
    
    public void setGbsSenha(String gbsSenha) {
        this.gbsSenha = gbsSenha;
    }

    
    @Column(name="gbs_nivel", nullable=false)
    public int getGbsNivel() {
        return this.gbsNivel;
    }
    
    public void setGbsNivel(int gbsNivel) {
        this.gbsNivel = gbsNivel;
    }

    
    @Column(name="gbs_ativo", nullable=false, length=1)
    public String getGbsAtivo() {
        return this.gbsAtivo;
    }
    
    public void setGbsAtivo(String gbsAtivo) {
        this.gbsAtivo = gbsAtivo;
    }




}


