package bean;
// Generated 22/09/2023 19:21:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GhsVendas generated by hbm2java
 */
@Entity
@Table(name="ghs_vendas"
    ,catalog="db_gabrielh"
)
public class GhsVendas  implements java.io.Serializable {


     private int idghsVendas;
     private double ghsValorTotal;
     private Date ghsDataVenda;
     private String ghsFormaPagamento;
     private String ghsStatusVenda;
     private GhsVendedor ghsVendedor;
     private GhsCliente ghsCliente;


    public GhsVendas() {
    }

	
    public GhsVendas(int idghsVendas, double ghsValorTotal, Date ghsDataVenda, String ghsFormaPagamento, String ghsStatusVenda, GhsVendedor ghsVendedor, GhsCliente ghsCliente) {
        this.idghsVendas = idghsVendas;
        this.ghsValorTotal = ghsValorTotal;
        this.ghsDataVenda = ghsDataVenda;
        this.ghsFormaPagamento = ghsFormaPagamento;
        this.ghsStatusVenda = ghsStatusVenda;
        this.ghsVendedor = ghsVendedor;
        this.ghsCliente = ghsCliente;
    }
   
     @Id 

    
    @Column(name="idghs_vendas", unique=true, nullable=false)
    public int getIdghsVendas() {
        return this.idghsVendas;
    }
    
    public void setIdghsVendas(int idghsVendas) {
        this.idghsVendas = idghsVendas;
    }

    
    @Column(name="ghs_valorTotal", nullable=false, precision=10)
    public double getGhsValorTotal() {
        return this.ghsValorTotal;
    }
    
    public void setGhsValorTotal(double ghsValorTotal) {
        this.ghsValorTotal = ghsValorTotal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ghs_dataVenda", nullable=false, length=19)
    public Date getGhsDataVenda() {
        return this.ghsDataVenda;
    }
    
    public void setGhsDataVenda(Date ghsDataVenda) {
        this.ghsDataVenda = ghsDataVenda;
    }

    
    @Column(name="ghs_formaPagamento", nullable=false, length=45)
    public String getGhsFormaPagamento() {
        return this.ghsFormaPagamento;
    }
    
    public void setGhsFormaPagamento(String ghsFormaPagamento) {
        this.ghsFormaPagamento = ghsFormaPagamento;
    }

    
    @Column(name="ghs_statusVenda", nullable=false, length=45)
    public String getGhsStatusVenda() {
        return this.ghsStatusVenda;
    }
    
    public void setGhsStatusVenda(String ghsStatusVenda) {
        this.ghsStatusVenda = ghsStatusVenda;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idghs_vendedor", nullable=false)
    public GhsVendedor getGhsVendedor() {
        return this.ghsVendedor;
    }
    
    public void setGhsVendedor(GhsProdutos ghsProdutos) {
        this.ghsVendedor = ghsVendedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idghs_cliente", nullable=false)
    public GhsCliente getGhsCliente() {
        return this.ghsCliente;
    }
    
    public void setGhsVendas(GhsVendas ghsVendas) {
        this.ghsCliente = ghsCliente;
    }



}


