package bean;
// Generated 16/09/2023 15:43:39 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GhsVendas generated by hbm2java
 */
@Entity
@Table(name="ghs_vendas"
    ,catalog="db_gabrielh"
)
public class GhsVendas  implements java.io.Serializable {


     private int idghsVendas;
     private Double ghsValorTotal;
     private Date ghsDataVenda;
     private String ghsFormaPagamento;
     private String ghsStatusVenda;
     private Set ghsVendasProdutoses = new HashSet(0);

    public GhsVendas() {
    }

	
    public GhsVendas(int idghsVendas, Double ghsValorTotal, Date ghsDataVenda, String ghsFormaPagamento, String ghsStatusVenda) {
        this.idghsVendas = idghsVendas;
        this.ghsValorTotal = ghsValorTotal;
        this.ghsDataVenda = ghsDataVenda;
        this.ghsFormaPagamento = ghsFormaPagamento;
        this.ghsStatusVenda = ghsStatusVenda;
    }
    public GhsVendas(int idghsVendas, Double ghsValorTotal, Date ghsDataVenda, String ghsFormaPagamento, String ghsStatusVenda, Set ghsVendasProdutoses) {
       this.idghsVendas = idghsVendas;
       this.ghsValorTotal = ghsValorTotal;
       this.ghsDataVenda = ghsDataVenda;
       this.ghsFormaPagamento = ghsFormaPagamento;
       this.ghsStatusVenda = ghsStatusVenda;
       this.ghsVendasProdutoses = ghsVendasProdutoses;
    }
   
     @Id 

    
    @Column(name="idghs_vendas", unique=true, nullable=false)
    public int getIdghsVendas() {
        return this.idghsVendas;
    }
    
    public void setIdghsVendas(int idghsVendas) {
        this.idghsVendas = idghsVendas;
    }

    
    @Column(name="ghs_valorTotal", nullable=false, precision=10)
    public Double getGhsValorTotal() {
        return this.ghsValorTotal;
    }
    
    public void setGhsValorTotal(Double ghsValorTotal) {
        this.ghsValorTotal = ghsValorTotal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ghs_dataVenda", nullable=false, length=19)
    public Date getGhsDataVenda() {
        return this.ghsDataVenda;
    }
    
    public void setGhsDataVenda(Date ghsDataVenda) {
        this.ghsDataVenda = ghsDataVenda;
    }

    
    @Column(name="ghs_formaPagamento", nullable=false, length=45)
    public String getGhsFormaPagamento() {
        return this.ghsFormaPagamento;
    }
    
    public void setGhsFormaPagamento(String ghsFormaPagamento) {
        this.ghsFormaPagamento = ghsFormaPagamento;
    }

    
    @Column(name="ghs_statusVenda", nullable=false, length=45)
    public String getGhsStatusVenda() {
        return this.ghsStatusVenda;
    }
    
    public void setGhsStatusVenda(String ghsStatusVenda) {
        this.ghsStatusVenda = ghsStatusVenda;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ghsVendas")
    public Set getGhsVendasProdutoses() {
        return this.ghsVendasProdutoses;
    }
    
    public void setGhsVendasProdutoses(Set ghsVendasProdutoses) {
        this.ghsVendasProdutoses = ghsVendasProdutoses;
    }




}


